
mqtt:
  broker: localhost
  port: 1883

sensor:
  - platform: mqtt
    name: "Assignment Temperature"
    state_topic: "home/deepika-2025/sensor"
    value_template: "{{ value_json.temperature }}"
    unit_of_measurement: "Â°C"

  - platform: mqtt
    name: "Assignment Humidity"
    state_topic: "home/deepika-2025/sensor"
    value_template: "{{ value_json.humidity }}"
    unit_of_measurement: "%"

  - platform: mqtt
    name: "Assignment Light"
    state_topic: "home/deepika-2025/sensor"
    value_template: "{{ value_json.light }}"
    unit_of_measurement: "lx"
